trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_VERSION: '18.x'
  BUILD_DIR: 'dist'
  REPO_NAME: '<your-github-username>/<your-repo-name>' # e.g. myuser/myrepo

steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: '$(NODE_VERSION)'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Install dependencies and build'

  - script: |
      npm install -g gh-pages
      npx gh-pages -d $(BUILD_DIR) -b gh-pages -r https://$(GH_TOKEN)@github.com/$(REPO_NAME).git
    displayName: 'Deploy to GitHub Pages'
    env:
      GH_TOKEN: $(GH_TOKEN)